### ISSUE TITLE
07 - Coletar ao menos 5 referências consultadas para o trabalho

### ISSUE THREAD

**Issue by Edj84** [Edj84/Lprog-T4#5]

**Comment by Lutterus** [comment]
https://learnxinyminutes.com/docs/standard-ml/

https://stackoverflow.com/questions/2168029/open-file-in-mlsmlnj

**Comment by Lutterus** [comment]
Gerador de palavras aleatórias usado: https://www.palabrasaleatorias.com/palavras-aleatorias.php
Gerador de sílabas para criação controlada de fragmentos: https://www.separarensilabas.com/index-pt.php

**Comment by Edj84** [comment]
Alice Manual - https://www.ps.uni-saarland.de/alice/manual/library/index.html
[A_Guide_to_Parsing_Algorithms_and_Terminology.pdf](https://github.com/Edj84/Lprog-T4/files/2546744/A_Guide_to_Parsing_Algorithms_and_Terminology.pdf)

**Comment by Lutterus** [comment]
http://sml-family.org/Basis/string.html#SIG:STRING.substring:VAL

http://rigaux.org/language-study/syntax-across-languages-per-language/SML.html

http://sml-family.org/Basis/list.html#SIG:LIST.length:VAL

https://cs.wellesley.edu/~cs251/slides/sml-lists_4up.pdf

https://www.cs.cornell.edu/courses/cs312/2004fa/lectures/rec21.html
